name: Update catalog.json from Google Sheets

on:
  workflow_dispatch:
  schedule:
    # cada 2 horas
    - cron: "0 */2 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Fetch catalog.json
        env:
          API_URL: ${{ secrets.SDC_API_URL }}
        run: node scripts/fetch_catalog.js

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if git diff --quiet; then
            echo "No changes."
            exit 0
          fi
          git add catalog.json
          git commit -m "chore: update catalog.json"
          git push
